#    This file is part of habib-2017-snRNAseq.
#    Copyright (C) 2019  Emir Turkes
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#    Emir Turkes can be contacted at emir.turkes@eturkes.com

version: "3"

services:
  all:
    image: eturkes/habib-2017-snrnaseq:R3.6.0v1
    volumes:
      - ".:/habib-2017-snRNAseq:rw"
    command: Rscript -e "source('/habib-2017-snRNAseq/R/run_all.R')"

  rstudio:
    image: eturkes/habib-2017-snrnaseq:R3.6.0v1
    volumes:
      - ".:/habib-2017-snRNAseq:rw"
    ports:
      - "127.0.0.1:8790:8787"
    environment:
      -  DISABLE_AUTH=true
